"""Static and residual IMU bias calibration for the movement supervisor.

Vertical mount (PCB sensor facing forward):

    chip +Z  ->  forward integrator
    chip +Y  ->  left integrator
    chip +X  ->  gravity reference (static bias only, not integrated)
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime
from typing import Callable, List, Optional, Tuple

from controller import Supervisor  # type: ignore[import-not-found]

from ble_imu import ImuSource, Sample

GRAVITY_M_S2 = 9.81

# Stationary window averaged at startup to estimate per-axis bias.
CALIB_S = 2.0

RESIDUAL_CALIBRATION_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "drift_calibration.json",
)

StepFn = Callable[[Supervisor, int, ImuSource], int]
AccelFn = Callable[[Sample], float]


@dataclass(frozen=True)
class StaticBiases:
    forward_g: float
    left_g: float
    gravity_g: float


@dataclass(frozen=True)
class ResidualBiases:
    forward_g: float
    left_g: float
    calibration_timestamp: str = "unknown"
    calibration_duration_s: float = 0.0


def run_static_calibration(
    sup: Supervisor,
    source: ImuSource,
    step: StepFn,
    timestep_ms: int,
    forward_accel_g: AccelFn,
    left_accel_g: AccelFn,
    gravity_accel_g: AccelFn,
) -> Optional[StaticBiases]:
    """Average IMU samples while the chip is held still for CALIB_S seconds."""
    print(
        f"[cal] static calibration: hold still for {CALIB_S:.1f} s "
        f"(vertical, PCB sensor facing forward)"
    )
    dt = timestep_ms / 1000.0
    n_steps = max(1, int(CALIB_S / dt))
    samples: List[Sample] = []
    for _ in range(n_steps):
        if step(sup, timestep_ms, source) == -1:
            return None
        sample = source.latest()
        if sample is not None:
            samples.append(sample)

    if not samples:
        print(
            "ERROR: no IMU samples during static calibration.",
            file=sys.stderr,
        )
        return None

    n = len(samples)
    biases = StaticBiases(
        forward_g=sum(forward_accel_g(s) for s in samples) / n,
        left_g=sum(left_accel_g(s) for s in samples) / n,
        gravity_g=sum(gravity_accel_g(s) for s in samples) / n,
    )
    print(
        f"[cal] static biases: forward={biases.forward_g:+.4f} g, "
        f"left={biases.left_g:+.4f} g, gravity={biases.gravity_g:+.4f} g"
    )
    return biases


def load_residual(
    path: str = RESIDUAL_CALIBRATION_PATH,
) -> Optional[ResidualBiases]:
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"[cal] warning: could not read {path}: {exc}", file=sys.stderr)
        return None
    return ResidualBiases(
        forward_g=float(data.get("residual_bias_forward_g", data.get("residual_bias_ax_g", 0.0))),
        left_g=float(data.get("residual_bias_left_g", data.get("residual_bias_ay_g", 0.0))),
        calibration_timestamp=str(data.get("calibration_timestamp", "unknown")),
        calibration_duration_s=float(data.get("calibration_duration_s", 0.0)),
    )


def save_residual(
    forward_g: float,
    left_g: float,
    duration_s: float,
    static_window_s: float = CALIB_S,
    path: str = RESIDUAL_CALIBRATION_PATH,
) -> None:
    payload = {
        "residual_bias_forward_g": forward_g,
        "residual_bias_left_g": left_g,
        "residual_bias_ax_g": forward_g,
        "residual_bias_ay_g": left_g,
        "calibration_duration_s": duration_s,
        "calibration_timestamp": datetime.now().isoformat(timespec="seconds"),
        "static_bias_window_s": static_window_s,
        "_note": (
            "Auto-generated by movement_supervisor --calibrate-drift. "
            "Subtracted in addition to the per-session static bias."
        ),
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def measure_residual_drift(
    sup: Supervisor,
    source: ImuSource,
    step: StepFn,
    static: StaticBiases,
    forward_accel_g: AccelFn,
    left_accel_g: AccelFn,
    duration_s: float,
    timestep_ms: int,
) -> Optional[Tuple[float, float, float, float]]:
    """Integrate freely while still; return (residual_forward_g, residual_left_g, drift_x, drift_y)."""
    print(
        f"[cal] drift calibration: hold perfectly still for {duration_s:.1f} s "
        "(no ZUPT / damping / clamp / LPF)"
    )

    v_forward = 0.0
    v_left = 0.0
    x_forward = 0.0
    x_left = 0.0

    last_seq, _ = source.latest_with_seq()
    last_sample_t = sup.getTime()
    t_start = sup.getTime()
    last_print_t = t_start

    while sup.getTime() - t_start < duration_s:
        if step(sup, timestep_ms, source) == -1:
            return None
        seq, sample = source.latest_with_seq()
        if sample is None or seq == last_seq:
            continue
        now = sup.getTime()
        sample_dt = now - last_sample_t
        last_sample_t = now
        last_seq = seq

        forward_ms2 = (forward_accel_g(sample) - static.forward_g) * GRAVITY_M_S2
        left_ms2 = (left_accel_g(sample) - static.left_g) * GRAVITY_M_S2

        v_forward += forward_ms2 * sample_dt
        v_left += left_ms2 * sample_dt
        x_forward += v_forward * sample_dt
        x_left += v_left * sample_dt

        if now - last_print_t >= 1.0:
            last_print_t = now
            elapsed = now - t_start
            print(
                f"[cal]   t={elapsed:5.1f}s  drift=({x_forward:+.3f}, "
                f"{x_left:+.3f}) m"
            )

    T = sup.getTime() - t_start
    if T <= 0.0:
        print("ERROR: drift calibration duration was 0; aborting", file=sys.stderr)
        return None

    residual_forward_g = (2.0 * x_forward / (T * T)) / GRAVITY_M_S2
    residual_left_g = (2.0 * x_left / (T * T)) / GRAVITY_M_S2
    return residual_forward_g, residual_left_g, x_forward, x_left


def correct_forward_g(
    sample: Sample,
    static: StaticBiases,
    residual: ResidualBiases,
    forward_accel_g: AccelFn,
) -> float:
    return forward_accel_g(sample) - static.forward_g - residual.forward_g


def correct_left_g(
    sample: Sample,
    static: StaticBiases,
    residual: ResidualBiases,
    left_accel_g: AccelFn,
) -> float:
    return left_accel_g(sample) - static.left_g - residual.left_g
